"""Declarative base and the portable column types every table is built from.

Two portability decisions live here so the rest of the layer never has to think
about them:

* ``UtcDateTime`` guarantees an aware UTC ``datetime`` on the way in *and* on
  the way out. PostgreSQL stores ``TIMESTAMP WITH TIME ZONE``; SQLite, used by
  the unit tests, has no timezone concept at all and would otherwise hand back
  naive values. A naive timestamp in an audit row is a correctness bug, so the
  type decorator closes the gap rather than trusting the driver.
* ``JsonDocument`` and ``StringList`` render as ``JSONB`` on PostgreSQL and as
  generic ``JSON`` elsewhere. Policy documents, scopes, and model allowlists all
  use them, which keeps the schema identical in shape across both dialects.

The naming convention is set explicitly so Alembic emits stable constraint
names; autogenerated names differ between dialects and make downgrades fail.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from sqlalchemy import JSON, DateTime, Dialect, MetaData
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.types import TypeDecorator

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


def utc_now() -> datetime:
    """Return the current instant as an aware UTC datetime."""
    return datetime.now(UTC)


class UtcDateTime(TypeDecorator[datetime]):
    """A timestamp that is always timezone-aware UTC in Python.

    Values are normalized to UTC before binding and re-tagged as UTC on load.
    A naive value on the way in is rejected rather than silently assumed to be
    UTC -- guessing an offset is how audit trails end up off by hours.
    """

    impl = DateTime(timezone=True)
    cache_ok = True

    def load_dialect_impl(self, dialect: Dialect) -> Any:
        return dialect.type_descriptor(DateTime(timezone=True))

    def process_bind_param(self, value: datetime | None, dialect: Dialect) -> datetime | None:
        if value is None:
            return None
        if value.tzinfo is None:
            raise ValueError("naive datetimes are not accepted; supply an aware UTC value")
        return value.astimezone(UTC)

    def process_result_value(self, value: datetime | None, dialect: Dialect) -> datetime | None:
        if value is None:
            return None
        if value.tzinfo is None:
            return value.replace(tzinfo=UTC)
        return value.astimezone(UTC)


JsonDocument = JSON().with_variant(postgresql.JSONB(), "postgresql")
"""Free-form JSON object. ``JSONB`` on PostgreSQL for indexing and containment."""

StringList = JSON().with_variant(postgresql.JSONB(), "postgresql")
"""A JSON array of strings (scopes, model allowlists)."""


class Base(DeclarativeBase):
    """Declarative base for every mapped class in the gateway."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
