"""Initial schema: tenants, api_keys, policies, provider_configs, audit_events.

Every table is written by hand rather than autogenerated so the constraint
names, the partial index on default policies, and the composite audit primary
key are explicit and reviewable. ``downgrade`` drops the tables in reverse
dependency order and is exercised by the migration integration test.

Revision ID: 0001
Revises:
Create Date: 2026-08-04
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# JSONB on PostgreSQL, generic JSON elsewhere -- identical to app.db.base.
JSON_DOC = sa.JSON().with_variant(postgresql.JSONB(), "postgresql")


def _timestamps() -> list[sa.Column[datetime]]:
    return [
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    ]


def upgrade() -> None:
    op.create_table(
        "tenants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="active", nullable=False),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_tenants"),
        sa.UniqueConstraint("slug", name="uq_tenants_slug"),
        sa.CheckConstraint("status IN ('active', 'suspended')", name="ck_tenants_status_known"),
    )

    op.create_table(
        "api_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("prefix", sa.String(length=64), nullable=False),
        sa.Column("key_hash", sa.String(length=128), nullable=False),
        sa.Column("scopes", JSON_DOC, nullable=False),
        sa.Column("status", sa.String(length=32), server_default="active", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_api_keys"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_api_keys_tenant_id_tenants",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("prefix", name="uq_api_keys_prefix"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_api_keys_tenant_id_name"),
        sa.CheckConstraint("status IN ('active', 'revoked')", name="ck_api_keys_status_known"),
    )
    op.create_index("ix_api_keys_tenant_id", "api_keys", ["tenant_id"])

    op.create_table(
        "policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("document", JSON_DOC, nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_policies"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_policies_tenant_id_tenants",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint(
            "tenant_id", "name", "version", name="uq_policies_tenant_id_name_version"
        ),
        sa.CheckConstraint("version > 0", name="ck_policies_version_positive"),
    )
    op.create_index("ix_policies_tenant_id", "policies", ["tenant_id"])
    # A composite UNIQUE does not constrain rows with a NULL tenant_id, so the
    # built-in default policy gets its own partial unique index.
    op.create_index(
        "uq_policies_default_name_version",
        "policies",
        ["name", "version"],
        unique=True,
        postgresql_where=sa.text("tenant_id IS NULL"),
        sqlite_where=sa.text("tenant_id IS NULL"),
    )

    op.create_table(
        "provider_configs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.String(length=64), nullable=False),
        sa.Column("provider_type", sa.String(length=64), nullable=False),
        # A reference to an environment variable. Never a credential value.
        sa.Column("secret_ref", sa.String(length=128), nullable=False),
        sa.Column("allowed_models", JSON_DOC, nullable=False),
        sa.Column("connect_timeout_seconds", sa.Integer(), server_default="5", nullable=False),
        sa.Column("read_timeout_seconds", sa.Integer(), server_default="60", nullable=False),
        sa.Column("max_retries", sa.Integer(), server_default="2", nullable=False),
        sa.Column("is_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_provider_configs"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_provider_configs_tenant_id_tenants",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("tenant_id", "alias", name="uq_provider_configs_tenant_id_alias"),
        sa.CheckConstraint(
            "length(secret_ref) BETWEEN 1 AND 128 AND secret_ref NOT LIKE '% %'",
            name="ck_provider_configs_secret_ref_is_reference",
        ),
        sa.CheckConstraint(
            "max_retries BETWEEN 0 AND 5", name="ck_provider_configs_max_retries_bounded"
        ),
    )
    op.create_index("ix_provider_configs_tenant_id", "provider_configs", ["tenant_id"])

    # No foreign keys and a composite (id, occurred_at) primary key: both are
    # prerequisites for converting this table to PostgreSQL declarative RANGE
    # partitioning on occurred_at without rewriting it.
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("api_key_id", sa.Uuid(), nullable=True),
        sa.Column("session_id_hash", sa.String(length=64), nullable=True),
        sa.Column("policy_id", sa.Uuid(), nullable=True),
        sa.Column("policy_version", sa.Integer(), nullable=True),
        sa.Column("provider_alias", sa.String(length=64), nullable=True),
        sa.Column("model_alias", sa.String(length=128), nullable=True),
        sa.Column("input_character_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_character_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("entity_counts", JSON_DOC, nullable=False),
        sa.Column("actions", JSON_DOC, nullable=False),
        sa.Column("blocked", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("block_reason_code", sa.String(length=64), nullable=True),
        sa.Column("provider_latency_ms", sa.Integer(), nullable=True),
        sa.Column("pipeline_latency_ms", sa.Integer(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("prompt_hmac", sa.Text(), nullable=True),
        sa.Column("response_hmac", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", "occurred_at", name="pk_audit_events"),
    )
    op.create_index(
        "ix_audit_events_tenant_id_occurred_at",
        "audit_events",
        ["tenant_id", "occurred_at"],
    )
    op.create_index("ix_audit_events_request_id", "audit_events", ["request_id"])


def downgrade() -> None:
    op.drop_index("ix_audit_events_request_id", table_name="audit_events")
    op.drop_index("ix_audit_events_tenant_id_occurred_at", table_name="audit_events")
    op.drop_table("audit_events")

    op.drop_index("ix_provider_configs_tenant_id", table_name="provider_configs")
    op.drop_table("provider_configs")

    op.drop_index("uq_policies_default_name_version", table_name="policies")
    op.drop_index("ix_policies_tenant_id", table_name="policies")
    op.drop_table("policies")

    op.drop_index("ix_api_keys_tenant_id", table_name="api_keys")
    op.drop_table("api_keys")

    op.drop_table("tenants")
